version: '3.9'

services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - gradle-cache-gateway:/app/.gradle
    working_dir: /app
    depends_on:
      - user-service
      - post-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
      - gradle-cache-user:/app/.gradle
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  post-service:
    build:
      context: .
      dockerfile: post-service/Dockerfile
    container_name: post-service
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
      - gradle-cache-post:/app/.gradle
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

volumes:
  gradle-cache-gateway:
  gradle-cache-user:
  gradle-cache-post:

networks:
  backend:
    driver: bridge