server:
  port: 8081

spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      # Connection settings
      host: localhost
      port: 6379
      password:
      timeout: 5000

      # Connection pool settings (Lettuce)
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 3000
          time-between-eviction-runs: 30s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


app:
  jwt:
    secret: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
    expiration: 864000

cache:
  redis:
    # Default TTL cho cache
    default-ttl: 3600
    # Prefix cho keys
    key-prefix: user


